# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import lcwp.proto.NetspeakService_pb2 as NetspeakService__pb2


class NetspeakServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Search = channel.unary_unary(
        '/netspeak.service.NetspeakService/Search',
        request_serializer=NetspeakService__pb2.SearchRequest.SerializeToString,
        response_deserializer=NetspeakService__pb2.SearchResponse.FromString,
        )
    self.GetCorpora = channel.unary_unary(
        '/netspeak.service.NetspeakService/GetCorpora',
        request_serializer=NetspeakService__pb2.CorporaRequest.SerializeToString,
        response_deserializer=NetspeakService__pb2.CorporaResponse.FromString,
        )


class NetspeakServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Search(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCorpora(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NetspeakServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Search': grpc.unary_unary_rpc_method_handler(
          servicer.Search,
          request_deserializer=NetspeakService__pb2.SearchRequest.FromString,
          response_serializer=NetspeakService__pb2.SearchResponse.SerializeToString,
      ),
      'GetCorpora': grpc.unary_unary_rpc_method_handler(
          servicer.GetCorpora,
          request_deserializer=NetspeakService__pb2.CorporaRequest.FromString,
          response_serializer=NetspeakService__pb2.CorporaResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'netspeak.service.NetspeakService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))